---
title: "Plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Examples of plotly

We're gonna look at NYC Airbnb data

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

# the Airbnb data
```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

# Plotly plots

## scatterplot
```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>%  # \n: make a new line
  plot_ly(x = ~lat, y = ~long, color = ~price, alpha = 0.5, 
          type = "scatter", mode = "markers", text = ~text_label)
```

## boxplot

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

## barplot

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

